### ISSUE TITLE
Can I ask the result?

### ISSUE THREAD

**Issue by doyeon-danny** [MizuhoAOKI/path_tracking#1]
Thank you for sharing your project.

I am researching about MPPI algorithm these days.
You compared many algorithms, then do you also have results like which controller has shortest length of paths etc.

Thank you.

**Comment by MizuhoAOKI** [comment]
@doyeon-danny 
Thank you for your comment.

I am afraid I have never tried evaluation yet.
This repository is mainly for understanding how the algorithms work.
Maybe I will try comparing tracking performances when I finish implementing most of my target algorithms.
